# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DppleEx' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DppleEx
   
  pod 'Alamofire', '~> 5.0.0-rc.2'
  pod 'Moya/RxSwift'
  pod 'KeychainAccess'
  pod 'RealmSwift'
  pod 'RxCocoa'
  pod 'CryptoSwift'
  pod 'AlamofireNetworkActivityLogger', '~> 3.0'
  pod 'ActionSheetPicker-3.0'
  pod 'ReactorKit'
  pod 'Swinject'
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'RxDataSources', '~> 4.0'
  pod 'Kingfisher', '~> 5.0'
  pod 'AppCenter'
  pod 'MarkdownView'
  pod 'SkeletonView'
  pod 'Then'
  pod 'SnapKit'  
  
end
